# Generated by Django 4.2.5 on 2025-10-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("answer_key", models.FileField(upload_to="answer_keys/")),
                (
                    "rubric_type",
                    models.CharField(
                        choices=[
                            ("ai_generated", "AI Generated"),
                            ("uploaded", "Uploaded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rubric_file",
                    models.FileField(blank=True, null=True, upload_to="rubrics/"),
                ),
                ("rubric_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("points", models.IntegerField()),
                ("description", models.TextField()),
                ("grading_notes", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
